### ISSUE TITLE
Mapping multiple tests as property

### ISSUE THREAD

**Issue by asub927** [bitcoder/cypress_with_mocha_junit_reporter_example#1]
@bitcoder - Does this fork support tagging multiple tests from x-ray mapped to mocha tests? I am using this in my project and able to map key, summary and description properties of X-ray and need to understand if I can map multiple tests into a mocha test as a property?

**Comment by bitcoder** [comment]
Unfortunately  no. Actually the limitation is on Xray side, as you can only mention one test issue key on a junit test. Mocha generates a junit report
